# Generated by Django 4.2.4 on 2023-08-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('handle_by', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('account_number', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=250)),
                ('bank_name', models.CharField(max_length=250)),
                ('gst_number', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.client')),
            ],
        ),
    ]
